// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// profile.js
export const FETCH_CHARACT_SUCCESS = 'FETCH_CHARACT_SUCCESS'
export const FETCH_CHARACT_FAILURE = 'FETCH_CHARACT_FAILURE'
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS'
export const FETCH_STATS_FAILURE = 'FETCH_STATS_FAILURE'
export const UPDATE_CHARACTERS = 'UPDATE_CHARACTERS'
export const UPDATE_STATS = 'UPDATE_STATS'
