// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const LOADER = 'LOADER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// profile.js
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE'

// posts.js
export const SAVE_POST = 'SAVE_POST'
export const PUSH_POST = 'PUSH_POST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'
export const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'

// category.js
export const SAVE_CAT = 'SAVE_CAT'
export const PUSH_CATEGORY = 'PUSH_CATEGORY'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
export const UPDATE_CAT = 'UPDATE_CAT'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

// media.js
export const SAVE_MEDIA = 'SAVE_MEDIA'
export const FETCH_MEDIA_SUCCESS = 'FETCH_MEDIA_SUCCESS'
export const FETCH_MEDIA_FAILURE = 'FETCH_MEDIA_FAILURE'
export const UPDATE_MEDIA = 'UPDATE_MEDIA'
export const DELETE_MEDIA = 'DELETE_MEDIA'

